---
- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Add all hosts in hosts file
  lineinfile: dest=/etc/hosts
              regexp="^127\.0\.1\.1"
              insertbefore=BOF
              line="127.0.1.1 {{ shortname }}\n{{ hostvars[item].ansible_host }} {{ hostvars[item].hostname }} {{ hostvars[item].shortname }}"
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.all }}"
