- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"
  tags:
    - change_hostname

- name: Change hostname in hosts file
  lineinfile: dest=/etc/hosts
              regexp="^127\.0\.1\.1"
              insertbefore=BOF
              line="127.0.1.1 {{ shortname }}"
  tags:
    - change_hostname

- name: Add hosts in hosts file
  lineinfile: dest=/etc/hosts
              regexp: ".*{{ item }}$"
              insertbefore="# The"
              line: "{{ hostvars[item].ansible_host }} {{ hostvars[item].hostname }}"
  when: hostvars[item].ansible_host is defined
  with_items:
    - "{{ groups.all }}"
