- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"
  tags:
    - change_hostname

- name: Change hostname in hosts file
  lineinfile: dest=/etc/hosts
              regexp="^127\.0\.1\.1"
              insertbefore=BOF
              line="127.0.1.1 {{ shortname }}"
  tags:
    - change_hostname

- name: Add hosts in hosts file
  lineinfile: dest=/etc/hosts
              regexp="^192"
              insertbefore="# The"
              line="192.168.0.100 master1.home.loc master1\n192.168.0.101 node1.home.loc node1\n192.168.0.102 node2.home.loc node2\n192.168.0.103 node3.home.loc node3\n"
