---
- name: Init kuber cluster
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16
  args:
    executable: /bin/bash

- name: Apply CNI
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  args:
    executable: /bin/bash

- name: Change permissions admin conf
  ansible.builtin.file:
    path: /etc/kubernetes/admin.conf
    mode: '0644'

- name: Create join command
  shell: kubeadm token create --print-join-command
  args:
    executable: /bin/bash
  register: command_message

- debug:
    msg="sudo {{ command_message.stdout }}"