---
- name: Off swap
  shell: swapoff -a
  args:
    executable: /bin/bash

- name: Write changes in fstab
  lineinfile: dest=/etc/fstab
              regexp="\/swap"
              insertbefore=BOF
              line="#/swap.img      none    swap    sw      0       0"

- name: Copy modules-load config
  ansible.builtin.copy:
    src: src/configs/modules/k8s.conf
    dest: /etc/modules-load.d/k8s.conf
    owner: root
    group: root
    mode: '0644'

- name: Copy kernel config
  ansible.builtin.copy:
    src: src/configs/kernel/k8s.conf
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root
    mode: '0644'

- name: Apply kernel config
  shell: sysctl --system
  args:
    executable: /bin/bash

- name: Reboot hosts and wait for it to restart
  reboot:
    msg: "Reboot initiated by Ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami